---
# Source: openhab/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-openhab-init
  labels:
    helm.sh/chart: openhab-1.5.2
    app.kubernetes.io/name: openhab
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.2.0"
    app.kubernetes.io/managed-by: Helm
data:
  enable-console-logging.sh: |
    echo 'Enabling console logging.'
    sed -i -E 's|(<AppenderRef ref="OSGI"/>).*|\1<AppenderRef ref="STDOUT"/>|' /openhab/userdata/etc/log4j2.xml
---
# Source: openhab/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-openhab-data
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openhab
    app.kubernetes.io/version: 3.2.0
    helm.sh/chart: openhab-1.5.2
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "nfs-client"
---
# Source: openhab/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-openhab
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openhab
    app.kubernetes.io/version: 3.2.0
    helm.sh/chart: openhab-1.5.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: openhab
    app.kubernetes.io/instance: release-name
---
# Source: openhab/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-openhab
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: openhab
    app.kubernetes.io/version: 3.2.0
    helm.sh/chart: openhab-1.5.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: openhab
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openhab
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: release-name-openhab
          image: "openhab/openhab:3.3.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
              - KILL
              - MKNOD
            runAsUser: 0
          env:
            - name: EXTRA_JAVA_OPTS
              value: -Duser.timezone=Europe/Berlin
            - name: TZ
              value: Europe/Berlin
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              subPath: addons
              mountPath: /openhab/addons
            - name: data
              subPath: conf
              mountPath: /openhab/conf
            - name: data
              subPath: userdata
              mountPath: /openhab/userdata
            - name: init
              mountPath: /etc/cont-init.d/enable-console-logging.sh
              subPath: enable-console-logging.sh
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 60
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: release-name-openhab-data
        - name: init
          configMap:
            name: release-name-openhab-init