{{- $values := $.Values.persistence -}}
{{- range $index, $PVC := .Values.persistence }}
    {{- $pvcName := printf "%v-%v" "openhab" $index -}}
    {{- if $PVC.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvcName }}
  {{- with (merge ($.Values.labels | default dict) (include "common.labels" $ | fromYaml)) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    {{- if $PVC.retain }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- with (merge ($.Values.annotations | default dict) (include "common.annotations" $ | fromYaml)) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ required (printf "accessMode is required for PVC %v" $pvcName) $PVC.accessMode | quote }}
  resources:
    requests:
      storage: {{ required (printf "size is required for PVC %v" $pvcName) $PVC.size | quote }}
  {{- if $PVC.storageClass }}
  storageClassName: {{ if (eq "-" $PVC.storageClass) }}""{{- else }}{{ $PVC.storageClass | quote }}{{- end }}
  {{- end }}
  {{- if $PVC.volumeName }}
  volumeName: {{ $PVC.volumeName | quote }}
  {{- end }}
{{- end -}}
{{- end -}}